"""Generate gestures from audio and write data files into an output folder.

The viewer (`visualize/output/visualize.html`) is checked in as-is and is NOT
regenerated by this script.

Outputs (default ./visualize/output/):
  - gen_rotation.npz   canonical generation: {poses [N,165], trans [N,3], betas [300], fps}
  - gen_position.npz      viewer-only: {joints [N,55,3], fps}
  - gt_position.npz       viewer-only: {joints [N,55,3], fps}
  - control_position.npz  optional viewer-only: {frames [K], joints [K], points [K,3], fps}
  - speech.wav            copy of input audio

Open `visualize/output/visualize.html` in Chrome/Firefox and drag the output
folder onto the drop zone to view.

Usage:
    python gen.py                                       # default audio + GT in visualize/input/
    python gen.py --audio path/to.wav --gt path/to.npz --out runs/exp1
"""

import argparse
import json
import os
import sys

# ---- our own args first; leave a clean argv for config.parse_args ----
_my_parser = argparse.ArgumentParser(add_help=False)
_my_parser.add_argument("--audio", default="visualize/input/2_scott_0_1_1.wav")
_my_parser.add_argument("--gt", default=None,
                        help="GT .npz with keys poses/trans/betas. "
                             "Defaults to audio path with .npz extension.")
_my_parser.add_argument("--out", default="visualize/output",
                        help="Output directory. Created if missing.")
_my_parser.add_argument("--mode", choices=("shortcut", "diffusion"), default="shortcut",
                        help="Generation backend. Shortcut remains the default; "
                             "diffusion uses configs/diffuser_rvqvae_128.yaml.")
_my_parser.add_argument("--config", "-c", default=None,
                        help="Advanced override for the generation config.")
_my_parser.add_argument("--control_json", default=None,
                        help="Optional sparse joint control JSON for diffusion mode.")
_my_parser.add_argument("--control_joint", "--control_joints",
                        dest="control_joints",
                        choices=("head", "left_wrist", "right_wrist", "all", "pelvis"),
                        default="left_wrist",
                        help="GT joint group for automatic control when --control_json is omitted.")
_my_parser.add_argument("--control_density", type=int, default=-1,
                        help="Automatic GT control density: 1/2/5 random frames, "
                             "50/100 percent random frames, or -1 for chunk end.")
_my_parser.add_argument("--control_timing", choices=("end", "chunk_end"), default=None,
                        help=argparse.SUPPRESS)
_my_parser.add_argument("--disable_auto_control", action="store_true",
                        help="Disable automatic GT control when --control_json is omitted.")
_my_parser.add_argument("--guidance_iters_early", type=int, default=5)
_my_parser.add_argument("--guidance_iters_late", type=int, default=30)
_my_parser.add_argument("--guidance_late_start", type=int, default=300,
                        help="Diffusion timestep threshold for late guidance iterations.")
_my_parser.add_argument("--guidance_scale_base", type=float, default=20.0)
_my_parser.add_argument("--guidance_weight", type=float, default=1.0)
_my_parser.add_argument("--guidance_chunk_delay", type=int, default=0,
                        help="Delay chunk k by k*N DDIM waves during batched guided diffusion. "
                             "Use 0 for the all-chunks-at-once schedule.")
_my_parser.add_argument("--guidance_log_every", type=int, default=5,
                        help="Print guidance loss at this optimizer-step interval. Use 0 to disable.")
_my_parser.add_argument("--guidance_freeze_root", type=lambda v: str(v).lower() not in ("0", "false", "no"),
                        default=True,
                        help="Detach generated translation inside the guidance loss.")
_my_parser.add_argument("--no-cache", action="store_true",
                        help="Force rebuild of MFA TextGrid + dataloader LMDB cache.")
_my_parser.add_argument("--unified-decoder-pth", default=None,
                        help="Optional unified RVQ-VAE decoder checkpoint. When set, "
                             "generation keeps the same latents but decodes them with "
                             "this unified decoder instead of the upper/hands/lower decoders.")
_my_parser.add_argument("--decoder-latent-mode", choices=("continuous", "discrete"),
                        default="continuous",
                        help="Use continuous generated latents directly, or quantize them "
                             "through the RVQ codebooks before decoding like early GestureLSM.")
_my_args, _rest = _my_parser.parse_known_args()
if _my_args.config is None:
    _my_args.config = (
        "configs/diffuser_rvqvae_128.yaml"
        if _my_args.mode == "diffusion" else
        "configs/shortcut_rvqvae_128_hf.yaml"
    )
sys.argv = [sys.argv[0], "-c", _my_args.config] + _rest

os.environ.setdefault("PYOPENGL_PLATFORM", "egl")
os.environ.setdefault("MASTER_ADDR", "127.0.0.3")
os.environ.setdefault("MASTER_PORT", "8678")

# Auto-enable HF offline mode if whisper-tiny.en is already cached. Avoids the
# ~5-10s HF Hub validation round-trip on every run.
_hf_cache = os.path.expanduser("~/.cache/huggingface/hub/models--openai--whisper-tiny.en")
if "HF_HUB_OFFLINE" not in os.environ and os.path.exists(_hf_cache):
    os.environ["HF_HUB_OFFLINE"] = "1"

import hashlib

import shutil
import subprocess
import warnings

import librosa
import numpy as np
import smplx
import torch
import torch.nn as nn
from loguru import logger
from transformers import pipeline

from dataloaders.build_vocab import Vocab  # noqa: F401  pickle needs it in __main__
from dataloaders.data_tools import joints_list
from models.vq.encdec import Decoder
from models.vq.model import RVQVAE
from utils import config, guidance as guidance_utils, other_tools, other_tools_hf, rotation_conversions as rc
# Imported for dynamic globals()[f'{part}_body_mask'] lookup below.
from utils.joints import hands_body_mask, lower_body_mask, upper_body_mask  # noqa: F401

warnings.simplefilter("ignore")

DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"


class UnifiedRVQVAEDecoder(nn.Module):
    def __init__(self, args, input_width=315, latent_width=384):
        super().__init__()
        self.latent_scale = args.vqvae_latent_scale
        self.decoder = Decoder(
            input_width,
            latent_width,
            args.down_t,
            args.stride_t,
            args.width,
            args.depth,
            args.dilation_growth_rate,
            activation=args.vq_act,
            norm=args.vq_norm,
        )

    def forward(self, latents):
        # Generation latents are [B, T, 384]; the decoder expects [B, 384, T].
        return self.decoder(latents.permute(0, 2, 1) * self.latent_scale)


# ===================================================================
# Trainer (audio-file variant of demo.BaseTrainer)
# ===================================================================
class HTMLTrainer:
    def __init__(self, args, cfg, audio_file, pose_file=None):
        # Stable per-audio tmp dir so MFA TextGrid + dataloader LMDB cache can be
        # reused across runs. Keyed on audio content + pose path so any input change
        # invalidates the cache automatically.
        with open(audio_file, "rb") as _af:
            _audio_hash = hashlib.md5(_af.read()).hexdigest()[:10]
        _pose_tag = hashlib.md5((pose_file or "").encode()).hexdigest()[:6]
        cache_tag = f"audio_{_audio_hash}_{_pose_tag}"
        self.tag = cache_tag
        tmp_dir = os.path.join(args.out_path, "custom", cache_tag)
        os.makedirs(tmp_dir, exist_ok=True)

        force_rebuild = getattr(_my_args, "no_cache", False)

        self.audio_path = os.path.join(tmp_dir, "tmp.wav")
        if force_rebuild or not os.path.exists(self.audio_path):
            shutil.copy(audio_file, self.audio_path)

        # Pose source for the dataloader (paired with the audio: used for seed +
        # length reference). Defaults to the .npz sibling of the audio file.
        if pose_file is None:
            pose_file = os.path.splitext(audio_file)[0] + ".npz"
        args.pose_file_path = os.path.abspath(pose_file)

        audio, ssr = librosa.load(self.audio_path, sr=args.audio_sr)

        # ASR → text → MFA → TextGrid. Skip if cached TextGrid already exists.
        lab_path = os.path.join(tmp_dir, "tmp.lab")
        self.textgrid_path = os.path.join(tmp_dir, "tmp.TextGrid")
        if force_rebuild and os.path.exists(self.textgrid_path):
            os.remove(self.textgrid_path)
        if os.path.exists(self.textgrid_path):
            logger.info(f"✓ cached TextGrid: {self.textgrid_path}")
        else:
            text = ASR_PIPE(audio, batch_size=8)["text"]
            with open(lab_path, "w", encoding="utf-8") as f:
                f.write(text)
            cmd = ["mfa", "align", tmp_dir, "english_us_arpa", "english_us_arpa", tmp_dir]
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                logger.warning(f"mfa stderr: {result.stderr}")

        # Optionally wipe the dataloader's LMDB cache so it rebuilds fresh.
        if force_rebuild:
            lmdb_dir = os.path.join(tmp_dir, "test", f"{args.pose_rep}_cache")
            if os.path.exists(lmdb_dir):
                shutil.rmtree(lmdb_dir)

        self.args = args
        self.cfg = cfg
        self.rank = 0
        args.textgrid_file_path = self.textgrid_path
        args.audio_file_path = self.audio_path
        args.tmp_dir = tmp_dir
        args.dataset = "beat_sep_single"

        # dataset / loader
        self.test_data = __import__(
            f"dataloaders.{args.dataset}", fromlist=["something"]
        ).CustomDataset(args, "test")
        self.test_loader = torch.utils.data.DataLoader(
            self.test_data, batch_size=1, shuffle=False,
            num_workers=args.loader_workers, drop_last=False,
        )

        # main model
        model_module = __import__(
            f"models.{cfg.model.model_name}", fromlist=["something"]
        )
        self.model = nn.DataParallel(
            getattr(model_module, cfg.model.g_name)(cfg), args.gpus
        ).cuda()

        # SMPLX
        self.smplx = smplx.create(
            args.data_path_1 + "smplx_models/",
            model_type="smplx", gender="NEUTRAL_2020",
            use_face_contour=False, num_betas=300,
            num_expression_coeffs=100, ext="npz", use_pca=False,
        ).to(self.rank).eval()

        # joint masks
        self.ori_joint_list = joints_list[args.ori_joints]
        self.joints = 55
        for part, key in [
            ("face", "beat_smplx_face"),
            ("upper", "beat_smplx_upper"),
            ("hands", "beat_smplx_hands"),
            ("lower", "beat_smplx_lower"),
        ]:
            mask = np.zeros(len(self.ori_joint_list) * 3)
            for jn in joints_list[key]:
                lo, hi = self.ori_joint_list[jn][1] - self.ori_joint_list[jn][0], self.ori_joint_list[jn][1]
                mask[lo:hi] = 1
            setattr(self, f"joint_mask_{part}", mask)

        # VQ-VAEs
        vq_module = __import__("models.motion_representation", fromlist=["something"])
        self.vq_model_face = self._face_vq(vq_module)
        self.vq_model_upper = self._rvqvae(78, "upper")
        self.vq_model_hands = self._rvqvae(180, "hands")
        self.vq_model_lower = self._rvqvae(54 if not args.use_trans else 57, "lower")
        for m in (self.vq_model_face, self.vq_model_upper,
                  self.vq_model_hands, self.vq_model_lower):
            m.eval().to(self.rank)
        self.vqvae_latent_scale = args.vqvae_latent_scale
        self.args.vae_length = 240

        # normalization
        self.use_trans = args.use_trans
        self.mean = np.load(args.mean_pose_path)
        self.std = np.load(args.std_pose_path)
        for part in ("upper", "hands", "lower"):
            mask = globals()[f"{part}_body_mask"]
            setattr(self, f"mean_{part}", torch.from_numpy(self.mean[mask]).cuda())
            setattr(self, f"std_{part}", torch.from_numpy(self.std[mask]).cuda())
        if self.use_trans:
            self.trans_mean = torch.from_numpy(np.load(args.mean_trans_path)).cuda()
            self.trans_std = torch.from_numpy(np.load(args.std_trans_path)).cuda()

        self.unified_pose_mask = []
        for joint in list(range(0, 22)) + list(range(25, 55)):
            self.unified_pose_mask.extend([joint * 6 + i for i in range(6)])
        self.unified_decoder = None
        if _my_args.unified_decoder_pth is not None:
            self.unified_decoder = self._unified_decoder(_my_args.unified_decoder_pth)

    def _face_vq(self, module):
        self.args.vae_layer = 2
        self.args.vae_length = 256
        self.args.vae_test_dim = 106
        model = getattr(module, "VQVAEConvZero")(self.args).to(self.rank)
        other_tools.load_checkpoints(
            model, "./datasets/hub/pretrained_vq/face_vertex_1layer_790.bin",
            self.args.e_name,
        )
        return model

    def _rvqvae(self, dim_pose, body_part):
        a = self.args
        model = RVQVAE(
            a, dim_pose, a.nb_code, a.code_dim, a.code_dim,
            a.down_t, a.stride_t, a.width, a.depth,
            a.dilation_growth_rate, a.vq_act, a.vq_norm,
        )
        model.load_state_dict(torch.load(getattr(a, f"vqvae_{body_part}_path"))["net"])
        return model

    def _unified_decoder(self, ckpt_path):
        ckpt = torch.load(ckpt_path, map_location="cpu")
        state = ckpt.get("decoder", ckpt)
        model = UnifiedRVQVAEDecoder(self.args).to(self.rank)
        model.load_state_dict(state, strict=True)
        model.eval()
        logger.info(f"Using unified RVQ-VAE decoder: {ckpt_path}")
        return model

    @staticmethod
    def _inverse_selection(filtered_t, selection_array, n):
        selection_array = torch.from_numpy(selection_array).to(filtered_t.device)
        out = torch.zeros((n, 165), device=filtered_t.device, dtype=filtered_t.dtype)
        idx = torch.where(selection_array == 1)[0]
        for i in range(n):
            out[i, idx] = filtered_t[i]
        return out

    def _build_control_tensors(self, n_frames):
        entries = getattr(self, "control_entries", None) or []
        if not entries:
            return None
        device = self.mean_upper.device
        hint = torch.zeros((n_frames, self.joints, 3), device=device)
        mask = torch.zeros((n_frames, self.joints), device=device)
        for entry in entries:
            frame = int(entry["frame"])
            joint = int(entry["joint"])
            if frame < 0 or frame >= n_frames:
                logger.warning(
                    f"Skipping control outside generated range: frame={frame}"
                )
                continue
            if joint < 0 or joint >= self.joints:
                raise ValueError(
                    f"Control joint index out of range [0,{self.joints}): {joint}"
                )
            hint[frame, joint] = torch.tensor(
                entry["xyz"], device=device, dtype=hint.dtype
            )
            mask[frame, joint] = float(entry.get("weight", 1.0))
        if mask.sum() <= 0:
            return None
        return {"hint": hint, "mask": mask}

    def _lower_latents_to_trans(self, lower_latents):
        return guidance_utils.lower_latents_to_trans(
            lower_latents,
            self.vq_model_lower,
            self.vqvae_latent_scale,
            self.trans_mean,
            self.trans_std,
        )

    @staticmethod
    def _quantize_model_latents(model, latents, sample_codebook_temp=0.5):
        quantized, _, _, _ = model.quantizer(
            latents.permute(0, 2, 1),
            sample_codebook_temp=sample_codebook_temp,
        )
        return quantized.permute(0, 2, 1)

    def _split_scaled_latents(self, full_latents):
        code_dim = self.vq_model_upper.code_dim
        rec_all_upper = full_latents[..., :code_dim] * self.vqvae_latent_scale
        rec_all_hands = full_latents[..., code_dim:code_dim * 2] * self.vqvae_latent_scale
        rec_all_lower = full_latents[..., code_dim * 2:code_dim * 3] * self.vqvae_latent_scale
        return rec_all_upper, rec_all_hands, rec_all_lower

    def _maybe_quantize_full_latents(self, full_latents):
        if _my_args.decoder_latent_mode != "discrete":
            return full_latents
        rec_all_upper, rec_all_hands, rec_all_lower = self._split_scaled_latents(full_latents)
        q_upper = self._quantize_model_latents(self.vq_model_upper, rec_all_upper)
        q_hands = self._quantize_model_latents(self.vq_model_hands, rec_all_hands)
        q_lower = self._quantize_model_latents(self.vq_model_lower, rec_all_lower)
        return torch.cat([q_upper, q_hands, q_lower], dim=-1) / self.vqvae_latent_scale

    def _decode_unified_latents(self, full_latents, freeze_root=False, trans_offset=None):
        full_latents = self._maybe_quantize_full_latents(full_latents)
        rec_full = self.unified_decoder(full_latents)
        pose_full = torch.zeros(
            (rec_full.shape[0], rec_full.shape[1], 330),
            device=rec_full.device,
            dtype=rec_full.dtype,
        )
        pose_full[..., self.unified_pose_mask] = rec_full[..., :len(self.unified_pose_mask)]

        rec_upper = pose_full[..., upper_body_mask]
        rec_hands = pose_full[..., hands_body_mask]
        rec_lower = pose_full[..., lower_body_mask]

        if self.use_trans:
            rec_trans_v = rec_full[..., len(self.unified_pose_mask):len(self.unified_pose_mask) + 3]
            rec_trans_v = rec_trans_v * self.trans_std + self.trans_mean
            rec_trans = torch.cumsum(rec_trans_v, dim=-2)
            rec_trans[..., 1] = rec_trans_v[..., 1]
            if trans_offset is not None:
                rec_trans = rec_trans + trans_offset.to(
                    device=rec_trans.device,
                    dtype=rec_trans.dtype,
                ).view(1, 1, 3)
        else:
            rec_trans = torch.zeros(
                (full_latents.shape[0], full_latents.shape[1], 3),
                device=full_latents.device,
                dtype=full_latents.dtype,
            )

        if freeze_root:
            rec_trans = rec_trans.detach()

        if self.args.pose_norm:
            rec_upper = rec_upper * self.std_upper + self.mean_upper
            rec_hands = rec_hands * self.std_hands + self.mean_hands
            rec_lower = rec_lower * self.std_lower + self.mean_lower

        return rec_upper, rec_hands, rec_lower, rec_trans

    def _latents_to_joints_local(self, full_latents, betas, freeze_root=True, trans_offset=None):
        rec_upper, rec_hands, rec_lower, rec_trans = self._decode_full_latents(
            full_latents,
            freeze_root=freeze_root,
            trans_offset=trans_offset,
        )
        bs_l, n_l = rec_lower.shape[:2]
        ru = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_upper.reshape(bs_l, n_l, 13, 6))
        ).reshape(bs_l * n_l, 13 * 3)
        rh = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_hands.reshape(bs_l, n_l, 30, 6))
        ).reshape(bs_l * n_l, 30 * 3)
        rl = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_lower[..., :54].reshape(bs_l, n_l, 9, 6))
        ).reshape(bs_l * n_l, 9 * 3)

        total = bs_l * n_l
        rec_pose = (
            self._inverse_selection(ru, self.joint_mask_upper, total)
            + self._inverse_selection(rl, self.joint_mask_lower, total)
            + self._inverse_selection(rh, self.joint_mask_hands, total)
        )
        aa = rec_pose.reshape(total, 55, 3)
        body_betas = (
            betas[:, None, :]
            .expand(bs_l, n_l, -1)
            .reshape(total, -1)
            .to(full_latents.device)
            .float()
        )
        out = self.smplx(
            betas=body_betas,
            global_orient=aa[:, 0],
            body_pose=aa[:, 1:22].reshape(total, 63),
            jaw_pose=aa[:, 22],
            leye_pose=aa[:, 23],
            reye_pose=aa[:, 24],
            left_hand_pose=aa[:, 25:40].reshape(total, 45),
            right_hand_pose=aa[:, 40:55].reshape(total, 45),
            transl=rec_trans.reshape(total, 3).float(),
            expression=torch.zeros(total, 100, device=full_latents.device),
            return_verts=False,
        )
        return out.joints[:, :55].reshape(bs_l, n_l, 55, 3)

    def _latent_chunk_to_joints(self, latent, betas, freeze_root=True, trans_offset=None):
        if self.unified_decoder is not None:
            sample = latent.squeeze(2).permute(0, 2, 1)
            return self._latents_to_joints_local(
                sample,
                betas,
                freeze_root=freeze_root,
                trans_offset=trans_offset,
            )
        return guidance_utils.latent_tensor_to_joints(
            latent,
            betas,
            self.smplx,
            self._inverse_selection,
            self.joint_mask_upper,
            self.joint_mask_lower,
            self.joint_mask_hands,
            self.vq_model_upper,
            self.vq_model_hands,
            self.vq_model_lower,
            self.vqvae_latent_scale,
            self.trans_mean,
            self.trans_std,
            self.mean_upper,
            self.std_upper,
            self.mean_hands,
            self.std_hands,
            self.mean_lower,
            self.std_lower,
            pose_norm=self.args.pose_norm,
            use_trans=self.use_trans,
            freeze_root=freeze_root,
            trans_offset=trans_offset,
        )

    def _stitch_chunk_latents(self, chunk_latents):
        return guidance_utils.stitch_chunk_latents(chunk_latents, self.args.pre_frames)

    def _decode_full_latents(self, full_latents, freeze_root=False, trans_offset=None):
        if self.unified_decoder is not None:
            return self._decode_unified_latents(
                full_latents,
                freeze_root=freeze_root,
                trans_offset=trans_offset,
            )
        if _my_args.decoder_latent_mode == "discrete":
            rec_up, rec_hn, rec_lo = self._split_scaled_latents(full_latents)
            rec_upper = self.vq_model_upper.latent2origin(rec_up)[0]
            rec_hands = self.vq_model_hands.latent2origin(rec_hn)[0]
            rec_lower = self.vq_model_lower.latent2origin(rec_lo)[0]
            if self.use_trans:
                rec_trans_v = rec_lower[..., -3:] * self.trans_std + self.trans_mean
                rec_trans = torch.cumsum(rec_trans_v, dim=-2)
                rec_trans[..., 1] = rec_trans_v[..., 1]
                if trans_offset is not None:
                    rec_trans = rec_trans + trans_offset.to(
                        device=rec_trans.device,
                        dtype=rec_trans.dtype,
                    ).view(1, 1, 3)
                rec_lower = rec_lower[..., :-3]
            else:
                rec_trans = torch.zeros(
                    (full_latents.shape[0], full_latents.shape[1], 3),
                    device=full_latents.device,
                    dtype=full_latents.dtype,
                )
            if freeze_root:
                rec_trans = rec_trans.detach()
            if self.args.pose_norm:
                rec_upper = rec_upper * self.std_upper + self.mean_upper
                rec_hands = rec_hands * self.std_hands + self.mean_hands
                rec_lower = rec_lower * self.std_lower + self.mean_lower
            return rec_upper, rec_hands, rec_lower, rec_trans
        return guidance_utils.decode_latents(
            full_latents,
            self.vq_model_upper,
            self.vq_model_hands,
            self.vq_model_lower,
            self.vqvae_latent_scale,
            self.trans_mean,
            self.trans_std,
            self.mean_upper,
            self.std_upper,
            self.mean_hands,
            self.std_hands,
            self.mean_lower,
            self.std_lower,
            pose_norm=self.args.pose_norm,
            use_trans=self.use_trans,
            freeze_root=freeze_root,
            trans_offset=trans_offset,
        )

    def _full_latents_to_joints(self, full_latents, betas, freeze_root=True):
        if self.unified_decoder is not None:
            return self._latents_to_joints_local(
                full_latents,
                betas,
                freeze_root=freeze_root,
            )
        return guidance_utils.latents_to_joints(
            full_latents,
            betas,
            self.smplx,
            self._inverse_selection,
            self.joint_mask_upper,
            self.joint_mask_lower,
            self.joint_mask_hands,
            self.vq_model_upper,
            self.vq_model_hands,
            self.vq_model_lower,
            self.vqvae_latent_scale,
            self.trans_mean,
            self.trans_std,
            self.mean_upper,
            self.std_upper,
            self.mean_hands,
            self.std_hands,
            self.mean_lower,
            self.std_lower,
            pose_norm=self.args.pose_norm,
            use_trans=self.use_trans,
            freeze_root=freeze_root,
        )

    def _latent_batch_to_window_joints(self, latent, betas, freeze_root, round_l):
        if self.unified_decoder is not None:
            chunk_latents = latent.squeeze(2).permute(0, 2, 1)
            full_latents = self._stitch_chunk_latents(chunk_latents)
            full_joints = self._latents_to_joints_local(
                full_latents,
                betas,
                freeze_root=freeze_root,
            )
            windows = []
            for i in range(chunk_latents.shape[0]):
                start = i * round_l
                end = start + self.args.pose_length
                windows.append(full_joints[:, start:end])
            return torch.cat(windows, dim=0)
        return guidance_utils.latent_batch_to_window_joints(
            latent,
            round_l,
            self.args.pose_length,
            self.args.pre_frames,
            betas,
            self.smplx,
            self._inverse_selection,
            self.joint_mask_upper,
            self.joint_mask_lower,
            self.joint_mask_hands,
            self.vq_model_upper,
            self.vq_model_hands,
            self.vq_model_lower,
            self.vqvae_latent_scale,
            self.trans_mean,
            self.trans_std,
            self.mean_upper,
            self.std_upper,
            self.mean_hands,
            self.std_hands,
            self.mean_lower,
            self.std_lower,
            pose_norm=self.args.pose_norm,
            use_trans=self.use_trans,
            freeze_root=freeze_root,
        )

    def _update_dynamic_seeds(self, x0, first_seed):
        return guidance_utils.update_dynamic_seeds(x0, first_seed, self.args.pre_frames)

    def _load_data(self, dict_data):
        tar_pose_raw = dict_data["pose"]
        tar_pose = tar_pose_raw[:, :, :165].to(self.rank)
        tar_contact = tar_pose_raw[:, :, 165:169].to(self.rank)
        tar_trans = dict_data["trans"].to(self.rank)
        tar_trans_v = dict_data["trans_v"].to(self.rank)
        tar_exps = dict_data["facial"].to(self.rank)
        audio_key = "audio" if "audio" in dict_data else "audio_onset"
        in_audio = dict_data[audio_key].to(self.rank)
        in_word = dict_data["word"].to(self.rank)
        tar_beta = dict_data["beta"].to(self.rank)
        tar_id = dict_data["id"].to(self.rank).long()
        bs, n = tar_pose.shape[0], tar_pose.shape[1]

        tp_hands = tar_pose[:, :, 25 * 3:55 * 3]
        tp_hands = rc.axis_angle_to_matrix(tp_hands.reshape(bs, n, 30, 3))
        tp_hands = rc.matrix_to_rotation_6d(tp_hands).reshape(bs, n, 30 * 6)

        tp_upper = tar_pose[:, :, self.joint_mask_upper.astype(bool)]
        tp_upper = rc.axis_angle_to_matrix(tp_upper.reshape(bs, n, 13, 3))
        tp_upper = rc.matrix_to_rotation_6d(tp_upper).reshape(bs, n, 13 * 6)

        tp_leg = tar_pose[:, :, self.joint_mask_lower.astype(bool)]
        tp_leg = rc.axis_angle_to_matrix(tp_leg.reshape(bs, n, 9, 3))
        tp_leg = rc.matrix_to_rotation_6d(tp_leg).reshape(bs, n, 9 * 6)
        tp_lower = tp_leg

        if self.args.pose_norm:
            tp_upper = (tp_upper - self.mean_upper) / self.std_upper
            tp_hands = (tp_hands - self.mean_hands) / self.std_hands
            tp_lower = (tp_lower - self.mean_lower) / self.std_lower

        if self.use_trans:
            tar_trans_v = (tar_trans_v - self.trans_mean) / self.trans_std
            tp_lower = torch.cat([tp_lower, tar_trans_v], dim=-1)

        l_up = self.vq_model_upper.map2latent(tp_upper)
        l_hn = self.vq_model_hands.map2latent(tp_hands)
        l_lo = self.vq_model_lower.map2latent(tp_lower)
        latent_in = torch.cat([l_up, l_hn, l_lo], dim=2) / self.vqvae_latent_scale

        return {
            "in_audio": in_audio, "in_word": in_word,
            "tar_trans": tar_trans, "tar_exps": tar_exps, "tar_beta": tar_beta,
            "tar_pose": tar_pose, "latent_in": latent_in,
            "tar_id": tar_id, "tar_contact": tar_contact,
        }

    def _g_test(self, loaded_data):
        """Mirror of demo.BaseTrainer._g_test — produces rec_pose / rec_trans."""
        a = self.args
        bs, n = loaded_data["tar_pose"].shape[0], loaded_data["tar_pose"].shape[1]
        tar_pose = loaded_data["tar_pose"]
        tar_trans = loaded_data["tar_trans"]
        in_word = loaded_data["in_word"]
        in_audio = loaded_data["in_audio"]
        in_x0 = loaded_data["latent_in"]
        in_seed = loaded_data["latent_in"]

        remain = n % 8
        if remain:
            tar_pose = tar_pose[:, :-remain]
            tar_trans = tar_trans[:, :-remain]
            in_word = in_word[:, :-remain]
            in_x0 = in_x0[:, :in_x0.shape[1] - (remain // a.vqvae_squeeze_scale)]
            in_seed = in_seed[:, :in_x0.shape[1]]
            n -= remain

        vsq = a.vqvae_squeeze_scale
        roundt = (n - a.pre_frames * vsq) // (a.pose_length - a.pre_frames * vsq)
        round_l = a.pose_length - a.pre_frames * vsq
        control_full = self._build_control_tensors(n)
        betas = loaded_data["tar_beta"][:, 0]

        audio_chunks, word_chunks, id_chunks = [], [], []
        seed_chunks = []
        first_seed = in_seed[:, :a.pre_frames]

        for i in range(roundt):
            audio_chunks.append(
                in_audio[:, i * (16000 // 30 * round_l):
                         (i + 1) * (16000 // 30 * round_l) + 16000 // 30 * a.pre_frames * vsq]
            )
            word_chunks.append(in_word[:, i * round_l:(i + 1) * round_l + a.pre_frames * vsq])
            id_chunks.append(loaded_data["tar_id"][:, i * round_l:(i + 1) * round_l + a.pre_frames])
            seed_chunks.append(torch.zeros_like(first_seed) if i > 0 else first_seed)

        final_chunks = None
        if control_full is not None and _my_args.mode == "diffusion":
            hint_chunks, mask_chunks = [], []
            for i in range(roundt):
                start = i * round_l
                end = start + a.pose_length
                chunk_hint = control_full["hint"][start:end].clone()
                chunk_mask = control_full["mask"][start:end].clone()
                if i > 0:
                    chunk_mask[:a.pre_frames * vsq] = 0
                hint_chunks.append(chunk_hint.unsqueeze(0))
                mask_chunks.append(chunk_mask.unsqueeze(0))

            hint_batch = torch.cat(hint_chunks, dim=0)
            mask_batch = torch.cat(mask_chunks, dim=0)
            if mask_batch.sum() > 0:
                cond = {"y": {
                    "audio_onset": torch.cat(audio_chunks, dim=0),
                    "word": torch.cat(word_chunks, dim=0),
                    "id": torch.cat(id_chunks, dim=0),
                    "seed": torch.cat(seed_chunks, dim=0),
                    "mask": (torch.zeros([roundt, 1, 1, a.pose_length], device=self.mean_upper.device) < 1),
                    "style_feature": torch.zeros([roundt, 512], device=self.mean_upper.device),
                    "control": {
                        "hint": hint_batch,
                        "mask": mask_batch,
                        "iters_early": _my_args.guidance_iters_early,
                        "iters_late": _my_args.guidance_iters_late,
                        "late_start": _my_args.guidance_late_start,
                        "scale": _my_args.guidance_scale_base,
                        "weight": _my_args.guidance_weight,
                        "chunk_delay": _my_args.guidance_chunk_delay,
                        "log_every": _my_args.guidance_log_every,
                        "freeze_root": _my_args.guidance_freeze_root,
                    },
                }}
                cond["y"]["guidance_fn"] = (
                    lambda x, freeze_root=True, betas=betas, round_l=round_l:
                    self._latent_batch_to_window_joints(x, betas, freeze_root, round_l)
                )
                cond["y"]["seed_update_fn"] = (
                    lambda x, seed, first_seed=first_seed:
                    self._update_dynamic_seeds(x, first_seed)
                )
                logger.info(
                    "Dynamic-seed global guidance active: "
                    f"{roundt} chunks, {int((mask_batch > 0).sum().item())} keyframes, "
                    f"chunk_delay={_my_args.guidance_chunk_delay}"
                )
                final_chunks = self.model(cond)["latents"].squeeze(2).permute(0, 2, 1)

        if final_chunks is None:
            rec_chunks = []
            last_sample = None
            for i in range(roundt):
                iseed = in_seed[:, i * round_l // vsq:(i + 1) * round_l // vsq + a.pre_frames]
                iseed = iseed[:, :a.pre_frames] if i == 0 else last_sample[:, -a.pre_frames:]
                cond = {"y": {
                    "audio_onset": audio_chunks[i],
                    "word": word_chunks[i],
                    "id": id_chunks[i],
                    "seed": iseed,
                    "mask": (torch.zeros([bs, 1, 1, a.pose_length], device=self.mean_upper.device) < 1),
                    "style_feature": torch.zeros([bs, 512], device=self.mean_upper.device),
                }}
                sample = self.model(cond)["latents"].squeeze(2).permute(0, 2, 1)
                last_sample = sample.clone()
                rec_chunks.append(sample)
            final_chunks = torch.cat(rec_chunks, dim=0)

        full_latents = self._stitch_chunk_latents(final_chunks)
        rec_upper, rec_hands, rec_lower, rec_trans = self._decode_full_latents(
            full_latents,
            freeze_root=False,
        )

        bs_l, n_l = rec_lower.shape[0], rec_lower.shape[1]
        ru = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_upper.reshape(bs_l, n_l, 13, 6))
        ).reshape(bs_l * n_l, 13 * 3)
        rh = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_hands.reshape(bs_l, n_l, 30, 6))
        ).reshape(bs_l * n_l, 30 * 3)
        rl = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_lower[..., :54].reshape(bs_l, n_l, 9, 6))
        ).reshape(bs_l * n_l, 9 * 3)

        N = bs_l * n_l
        rec_pose = (self._inverse_selection(ru, self.joint_mask_upper, N)
                    + self._inverse_selection(rl, self.joint_mask_lower, N)
                    + self._inverse_selection(rh, self.joint_mask_hands, N))
        rec_pose[:, 66:69] = tar_pose.reshape(bs * n, 55 * 3)[:N, 66:69]

        n = n - ((n - a.pre_frames * vsq) % (a.pose_length - a.pre_frames * vsq))
        return {
            "rec_pose_aa": rec_pose.reshape(bs_l, n_l, 165),
            "rec_trans": rec_trans,
            "tar_beta": loaded_data["tar_beta"][:, :n_l],
        }

    @torch.no_grad()
    def run_inference(self):
        self.model.eval()
        self.smplx.eval()
        for batch in self.test_loader:
            loaded = self._load_data(batch)
            return self._g_test(loaded)
        raise RuntimeError("test loader produced no batches")


# ===================================================================
# SMPLX → joint positions
# ===================================================================
@torch.no_grad()
def smplx_to_joints(smplx_model, rec_pose_aa, rec_trans, betas):
    """rec_pose_aa: [N, 165], rec_trans: [N, 3], betas: [300] → joints [N, 55, 3]."""
    N = rec_pose_aa.shape[0]
    aa = rec_pose_aa.reshape(N, 55, 3)
    body_betas = betas.unsqueeze(0).expand(N, -1).to(rec_pose_aa.device).float()
    out = smplx_model(
        betas=body_betas,
        global_orient=aa[:, 0],
        body_pose=aa[:, 1:22].reshape(N, 63),
        jaw_pose=aa[:, 22],
        leye_pose=aa[:, 23],
        reye_pose=aa[:, 24],
        left_hand_pose=aa[:, 25:40].reshape(N, 45),
        right_hand_pose=aa[:, 40:55].reshape(N, 45),
        transl=rec_trans.float(),
        expression=torch.zeros(N, 100, device=rec_pose_aa.device),
        return_verts=False,
    )
    return out.joints[:, :55].detach().cpu().numpy()  # [N, 55, 3]


# ===================================================================
# Main
# ===================================================================
ASR_PIPE = None  # lazily initialised in main


def load_control_entries(path):
    if path is None:
        return []
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    entries = data.get("controls", data) if isinstance(data, dict) else data
    if not isinstance(entries, list):
        raise ValueError("control_json must be a list or an object with a 'controls' list")
    for entry in entries:
        if not all(k in entry for k in ("frame", "joint", "xyz")):
            raise ValueError("Each control entry must contain frame, joint, and xyz")
        if len(entry["xyz"]) != 3:
            raise ValueError(f"Control xyz must have length 3: {entry}")
    return entries


def expected_generated_frames(n_frames, args):
    remain = n_frames % 8
    if remain:
        n_frames -= remain
    seed_frames = args.pre_frames * args.vqvae_squeeze_scale
    round_l = args.pose_length - seed_frames
    if n_frames < args.pose_length:
        return 0
    return n_frames - ((n_frames - seed_frames) % round_l)


CONTROL_JOINT_GROUPS = {
    "head": (15,),
    "left_wrist": (20,),
    "right_wrist": (21,),
    "all": (15, 20, 21),
    "pelvis": (0,),
}


def _control_frames_for_density(last_frame, args, density):
    if density == -1:
        seed_frames = args.pre_frames * args.vqvae_squeeze_scale
        round_l = args.pose_length - seed_frames
        frames = list(range(args.pose_length - 1, last_frame + 1, round_l))
        if not frames or frames[-1] != last_frame:
            frames.append(last_frame)
        return frames

    n_frames = last_frame + 1
    if density in (1, 2, 5):
        frame_count = min(n_frames, density)
    else:
        frame_count = min(n_frames, int(n_frames * density / 100))
    if frame_count <= 0:
        return []

    rng = np.random.default_rng(42)
    frames = np.asarray(rng.choice(n_frames, frame_count, replace=False), dtype=np.int64)
    frames.sort()
    return frames.tolist()


def build_gt_control_entries(gt_joints, max_frame, args, control_joints, control_density):
    joints = CONTROL_JOINT_GROUPS[control_joints]
    last_frame = min(max_frame, gt_joints.shape[0]) - 1
    if last_frame < 0:
        return []

    frames = _control_frames_for_density(last_frame, args, int(control_density))
    entries = []
    for frame in frames:
        for joint in joints:
            xyz = gt_joints[frame, joint].copy()
            entries.append({
                "frame": int(frame),
                "joint": int(joint),
                "xyz": xyz.tolist(),
            })
    return entries


@logger.catch
def main():
    global ASR_PIPE
    args, cfg = config.parse_args()
    other_tools_hf.set_random_seed(args)
    control_entries = load_control_entries(_my_args.control_json)
    if control_entries and cfg.model.g_name != "GestureDiffusion":
        raise ValueError("--control_json requires --mode diffusion or a GestureDiffusion config")

    out_dir = os.path.abspath(_my_args.out)
    os.makedirs(out_dir, exist_ok=True)
    logger.info(f"Output dir: {out_dir}")

    ASR_PIPE = pipeline(
        "automatic-speech-recognition",
        model="openai/whisper-tiny.en",
        chunk_length_s=30,
        device=DEVICE,
    )

    # Resolve GT npz path once: used both by the dataloader (as pose source) and
    # by the per-frame GT joint comparison below.
    gt_path = _my_args.gt or os.path.splitext(_my_args.audio)[0] + ".npz"
    if not os.path.exists(gt_path):
        raise FileNotFoundError(f"GT npz not found: {gt_path}")

    trainer = HTMLTrainer(args, cfg, audio_file=_my_args.audio, pose_file=gt_path)
    other_tools.load_checkpoints(trainer.model, args.test_ckpt, args.g_name)

    # ---- Ground truth ----
    gt = np.load(gt_path, allow_pickle=True)
    gt_pose_aa = torch.from_numpy(gt["poses"]).float().to(DEVICE)
    gt_trans = torch.from_numpy(gt["trans"]).float().to(DEVICE)
    gt_betas = torch.from_numpy(gt["betas"]).float().to(DEVICE)
    gt_joints = smplx_to_joints(trainer.smplx, gt_pose_aa, gt_trans, gt_betas)

    if not control_entries and not _my_args.disable_auto_control:
        generated_len = expected_generated_frames(gt_joints.shape[0], args)
        control_density = _my_args.control_density
        if _my_args.control_timing is not None:
            control_density = -1 if _my_args.control_timing == "chunk_end" else 1
        control_entries = build_gt_control_entries(
            gt_joints,
            generated_len,
            args,
            _my_args.control_joints,
            control_density,
        )
        density_name = "chunk_end" if int(control_density) == -1 else str(control_density)
        logger.info(
            f"Using sparse GT {_my_args.control_joints} control points "
            f"(density_{density_name}): {len(control_entries)} keyframes"
        )
    trainer.control_entries = control_entries if _my_args.mode == "diffusion" else []

    # ---- Generation ----
    out = trainer.run_inference()
    rec_pose_aa = out["rec_pose_aa"].reshape(-1, 165)
    rec_trans = out["rec_trans"].reshape(-1, 3)
    betas = out["tar_beta"][0, 0]
    gen_joints = smplx_to_joints(trainer.smplx, rec_pose_aa, rec_trans, betas)

    for entry in control_entries:
        frame = int(entry["frame"])
        joint = int(entry["joint"])
        if 0 <= frame < gen_joints.shape[0] and 0 <= joint < gen_joints.shape[1]:
            target = np.asarray(entry["xyz"], dtype=np.float32)
            err = np.linalg.norm(gen_joints[frame, joint] - target)
            logger.info(
                f"Final control error frame={frame} joint={joint}: {err:.6f} "
                f"gen={gen_joints[frame, joint].tolist()} target={target.tolist()}"
            )

    fps = int(args.pose_fps)

    # ---- Write canonical generation (rotations + translation + betas) ----
    np.savez(
        os.path.join(out_dir, "gen_rotation.npz"),
        poses=rec_pose_aa.detach().cpu().numpy(),
        trans=rec_trans.detach().cpu().numpy(),
        betas=betas.detach().cpu().numpy(),
        fps=np.int32(fps),
    )

    # ---- Write viewer-only joint positions ----
    np.savez(
        os.path.join(out_dir, "gen_position.npz"),
        joints=gen_joints,
        fps=np.int32(fps),
    )
    np.savez(
        os.path.join(out_dir, "gt_position.npz"),
        joints=gt_joints,
        fps=np.int32(fps),
    )
    valid_controls = [
        entry for entry in control_entries
        if 0 <= int(entry["frame"]) < gen_joints.shape[0]
        and 0 <= int(entry["joint"]) < gen_joints.shape[1]
    ]
    if valid_controls:
        np.savez(
            os.path.join(out_dir, "control_position.npz"),
            frames=np.array([int(entry["frame"]) for entry in valid_controls], dtype=np.int32),
            joints=np.array([int(entry["joint"]) for entry in valid_controls], dtype=np.int32),
            points=np.array([entry["xyz"] for entry in valid_controls], dtype=np.float32),
            fps=np.int32(fps),
        )

    # ---- Copy audio ----
    shutil.copy(_my_args.audio, os.path.join(out_dir, "speech.wav"))

    logger.info(
        f"Wrote {out_dir} "
        f"(gen {gen_joints.shape[0]} fr | gt {gt_joints.shape[0]} fr @ {fps} fps)"
    )
    logger.info(f"Open: {os.path.join(out_dir, 'visualize.html')}")


if __name__ == "__main__":
    import sys
    main()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(0)
