"""Generate gestures from audio and write data files into an output folder.

The viewer (`visualize/output/visualize.html`) is checked in as-is and is NOT
regenerated by this script.

Outputs (default ./visualize/output/):
  - gen_rotation.npz   canonical generation: {poses [N,165], trans [N,3], betas [300], fps}
  - gen_position.npz   viewer-only: {joints [N,55,3], fps}
  - gt_position.npz    viewer-only: {joints [N,55,3], fps}
  - speech.wav         copy of input audio

Open `visualize/output/visualize.html` in Chrome/Firefox and drag the output
folder onto the drop zone to view.

Usage:
    python gen.py                                       # default audio + GT in visualize/input/
    python gen.py --audio path/to.wav --gt path/to.npz --out runs/exp1
"""

import argparse
import os
import sys

# ---- our own args first; leave a clean argv for config.parse_args ----
_my_parser = argparse.ArgumentParser(add_help=False)
_my_parser.add_argument("--audio", default="visualize/input/2_scott_0_1_1.wav")
_my_parser.add_argument("--gt", default=None,
                        help="GT .npz with keys poses/trans/betas. "
                             "Defaults to audio path with .npz extension.")
_my_parser.add_argument("--out", default="visualize/output",
                        help="Output directory. Created if missing.")
_my_parser.add_argument("--config", "-c", default="configs/shortcut_rvqvae_128_hf.yaml")
_my_args, _rest = _my_parser.parse_known_args()
sys.argv = [sys.argv[0], "-c", _my_args.config] + _rest

os.environ.setdefault("PYOPENGL_PLATFORM", "egl")
os.environ.setdefault("MASTER_ADDR", "127.0.0.3")
os.environ.setdefault("MASTER_PORT", "8678")

import shutil
import subprocess
import time
import warnings

import librosa
import numpy as np
import smplx
import torch
import torch.nn as nn
from loguru import logger
from transformers import pipeline

from dataloaders.build_vocab import Vocab  # noqa: F401  pickle needs it in __main__
from dataloaders.data_tools import joints_list
from models.vq.model import RVQVAE
from utils import config, other_tools, other_tools_hf, rotation_conversions as rc
# Imported for dynamic globals()[f'{part}_body_mask'] lookup below.
from utils.joints import hands_body_mask, lower_body_mask, upper_body_mask  # noqa: F401

warnings.simplefilter("ignore")

DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"


# ===================================================================
# Trainer (audio-file variant of demo.BaseTrainer)
# ===================================================================
class HTMLTrainer:
    def __init__(self, args, cfg, audio_file, pose_file=None):
        time_local = time.localtime()
        tag = "%02d%02d_%02d%02d%02d_" % (
            time_local[1], time_local[2], time_local[3], time_local[4], time_local[5]
        )
        self.tag = tag
        tmp_dir = os.path.join(args.out_path, "custom", tag + "html")
        os.makedirs(tmp_dir, exist_ok=True)

        self.audio_path = os.path.join(tmp_dir, "tmp.wav")
        shutil.copy(audio_file, self.audio_path)

        # Pose source for the dataloader (paired with the audio: used for seed +
        # length reference). Defaults to the .npz sibling of the audio file.
        if pose_file is None:
            pose_file = os.path.splitext(audio_file)[0] + ".npz"
        args.pose_file_path = os.path.abspath(pose_file)

        audio, ssr = librosa.load(self.audio_path, sr=args.audio_sr)

        # ASR → text → MFA → TextGrid (same as demo.py)
        lab_path = os.path.join(tmp_dir, "tmp.lab")
        self.textgrid_path = os.path.join(tmp_dir, "tmp.TextGrid")
        text = ASR_PIPE(audio, batch_size=8)["text"]
        with open(lab_path, "w", encoding="utf-8") as f:
            f.write(text)
        cmd = ["mfa", "align", tmp_dir, "english_us_arpa", "english_us_arpa", tmp_dir]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            logger.warning(f"mfa stderr: {result.stderr}")

        self.args = args
        self.cfg = cfg
        self.rank = 0
        args.textgrid_file_path = self.textgrid_path
        args.audio_file_path = self.audio_path
        args.tmp_dir = tmp_dir

        # dataset / loader
        self.test_data = __import__(
            f"dataloaders.{args.dataset}", fromlist=["something"]
        ).CustomDataset(args, "test")
        self.test_loader = torch.utils.data.DataLoader(
            self.test_data, batch_size=1, shuffle=False,
            num_workers=args.loader_workers, drop_last=False,
        )

        # main model
        model_module = __import__(
            f"models.{cfg.model.model_name}", fromlist=["something"]
        )
        self.model = nn.DataParallel(
            getattr(model_module, cfg.model.g_name)(cfg), args.gpus
        ).cuda()

        # SMPLX
        self.smplx = smplx.create(
            args.data_path_1 + "smplx_models/",
            model_type="smplx", gender="NEUTRAL_2020",
            use_face_contour=False, num_betas=300,
            num_expression_coeffs=100, ext="npz", use_pca=False,
        ).to(self.rank).eval()

        # joint masks
        self.ori_joint_list = joints_list[args.ori_joints]
        self.joints = 55
        for part, key in [
            ("face", "beat_smplx_face"),
            ("upper", "beat_smplx_upper"),
            ("hands", "beat_smplx_hands"),
            ("lower", "beat_smplx_lower"),
        ]:
            mask = np.zeros(len(self.ori_joint_list) * 3)
            for jn in joints_list[key]:
                lo, hi = self.ori_joint_list[jn][1] - self.ori_joint_list[jn][0], self.ori_joint_list[jn][1]
                mask[lo:hi] = 1
            setattr(self, f"joint_mask_{part}", mask)

        # VQ-VAEs
        vq_module = __import__("models.motion_representation", fromlist=["something"])
        self.vq_model_face = self._face_vq(vq_module)
        self.vq_model_upper = self._rvqvae(78, "upper")
        self.vq_model_hands = self._rvqvae(180, "hands")
        self.vq_model_lower = self._rvqvae(54 if not args.use_trans else 57, "lower")
        for m in (self.vq_model_face, self.vq_model_upper,
                  self.vq_model_hands, self.vq_model_lower):
            m.eval().to(self.rank)
        self.vqvae_latent_scale = args.vqvae_latent_scale
        self.args.vae_length = 240

        # normalization
        self.use_trans = args.use_trans
        self.mean = np.load(args.mean_pose_path)
        self.std = np.load(args.std_pose_path)
        for part in ("upper", "hands", "lower"):
            mask = globals()[f"{part}_body_mask"]
            setattr(self, f"mean_{part}", torch.from_numpy(self.mean[mask]).cuda())
            setattr(self, f"std_{part}", torch.from_numpy(self.std[mask]).cuda())
        if self.use_trans:
            self.trans_mean = torch.from_numpy(np.load(args.mean_trans_path)).cuda()
            self.trans_std = torch.from_numpy(np.load(args.std_trans_path)).cuda()

    def _face_vq(self, module):
        self.args.vae_layer = 2
        self.args.vae_length = 256
        self.args.vae_test_dim = 106
        model = getattr(module, "VQVAEConvZero")(self.args).to(self.rank)
        other_tools.load_checkpoints(
            model, "./datasets/hub/pretrained_vq/face_vertex_1layer_790.bin",
            self.args.e_name,
        )
        return model

    def _rvqvae(self, dim_pose, body_part):
        a = self.args
        model = RVQVAE(
            a, dim_pose, a.nb_code, a.code_dim, a.code_dim,
            a.down_t, a.stride_t, a.width, a.depth,
            a.dilation_growth_rate, a.vq_act, a.vq_norm,
        )
        model.load_state_dict(torch.load(getattr(a, f"vqvae_{body_part}_path"))["net"])
        return model

    @staticmethod
    def _inverse_selection(filtered_t, selection_array, n):
        selection_array = torch.from_numpy(selection_array).cuda()
        out = torch.zeros((n, 165)).cuda()
        idx = torch.where(selection_array == 1)[0]
        for i in range(n):
            out[i, idx] = filtered_t[i]
        return out

    def _load_data(self, dict_data):
        tar_pose_raw = dict_data["pose"]
        tar_pose = tar_pose_raw[:, :, :165].to(self.rank)
        tar_contact = tar_pose_raw[:, :, 165:169].to(self.rank)
        tar_trans = dict_data["trans"].to(self.rank)
        tar_trans_v = dict_data["trans_v"].to(self.rank)
        tar_exps = dict_data["facial"].to(self.rank)
        in_audio = dict_data["audio"].to(self.rank)
        in_word = dict_data["word"].to(self.rank)
        tar_beta = dict_data["beta"].to(self.rank)
        tar_id = dict_data["id"].to(self.rank).long()
        bs, n = tar_pose.shape[0], tar_pose.shape[1]

        tp_hands = tar_pose[:, :, 25 * 3:55 * 3]
        tp_hands = rc.axis_angle_to_matrix(tp_hands.reshape(bs, n, 30, 3))
        tp_hands = rc.matrix_to_rotation_6d(tp_hands).reshape(bs, n, 30 * 6)

        tp_upper = tar_pose[:, :, self.joint_mask_upper.astype(bool)]
        tp_upper = rc.axis_angle_to_matrix(tp_upper.reshape(bs, n, 13, 3))
        tp_upper = rc.matrix_to_rotation_6d(tp_upper).reshape(bs, n, 13 * 6)

        tp_leg = tar_pose[:, :, self.joint_mask_lower.astype(bool)]
        tp_leg = rc.axis_angle_to_matrix(tp_leg.reshape(bs, n, 9, 3))
        tp_leg = rc.matrix_to_rotation_6d(tp_leg).reshape(bs, n, 9 * 6)
        tp_lower = tp_leg

        if self.args.pose_norm:
            tp_upper = (tp_upper - self.mean_upper) / self.std_upper
            tp_hands = (tp_hands - self.mean_hands) / self.std_hands
            tp_lower = (tp_lower - self.mean_lower) / self.std_lower

        if self.use_trans:
            tar_trans_v = (tar_trans_v - self.trans_mean) / self.trans_std
            tp_lower = torch.cat([tp_lower, tar_trans_v], dim=-1)

        l_up = self.vq_model_upper.map2latent(tp_upper)
        l_hn = self.vq_model_hands.map2latent(tp_hands)
        l_lo = self.vq_model_lower.map2latent(tp_lower)
        latent_in = torch.cat([l_up, l_hn, l_lo], dim=2) / self.vqvae_latent_scale

        return {
            "in_audio": in_audio, "in_word": in_word,
            "tar_trans": tar_trans, "tar_exps": tar_exps, "tar_beta": tar_beta,
            "tar_pose": tar_pose, "latent_in": latent_in,
            "tar_id": tar_id, "tar_contact": tar_contact,
        }

    def _g_test(self, loaded_data):
        """Mirror of demo.BaseTrainer._g_test — produces rec_pose / rec_trans."""
        a = self.args
        bs, n = loaded_data["tar_pose"].shape[0], loaded_data["tar_pose"].shape[1]
        j = self.joints
        tar_pose = loaded_data["tar_pose"]
        tar_trans = loaded_data["tar_trans"]
        in_word = loaded_data["in_word"]
        in_audio = loaded_data["in_audio"]
        in_x0 = loaded_data["latent_in"]
        in_seed = loaded_data["latent_in"]

        remain = n % 8
        if remain:
            tar_pose = tar_pose[:, :-remain]
            tar_trans = tar_trans[:, :-remain]
            in_word = in_word[:, :-remain]
            in_x0 = in_x0[:, :in_x0.shape[1] - (remain // a.vqvae_squeeze_scale)]
            in_seed = in_seed[:, :in_x0.shape[1]]
            n -= remain

        rec_up, rec_hn, rec_lo = [], [], []
        vsq = a.vqvae_squeeze_scale
        roundt = (n - a.pre_frames * vsq) // (a.pose_length - a.pre_frames * vsq)
        round_l = a.pose_length - a.pre_frames * vsq
        last_sample = None

        for i in range(roundt):
            iw = in_word[:, i * round_l:(i + 1) * round_l + a.pre_frames * vsq]
            ia = in_audio[:, i * (16000 // 30 * round_l):
                          (i + 1) * (16000 // 30 * round_l) + 16000 // 30 * a.pre_frames * vsq]
            iid = loaded_data["tar_id"][:, i * round_l:(i + 1) * round_l + a.pre_frames]
            ix0 = in_x0[:, i * round_l // vsq:(i + 1) * round_l // vsq + a.pre_frames]
            iseed = in_seed[:, i * round_l // vsq:(i + 1) * round_l // vsq + a.pre_frames]
            iseed = iseed[:, :a.pre_frames] if i == 0 else last_sample[:, -a.pre_frames:]

            cond = {"y": {
                "audio_onset": ia, "word": iw, "id": iid, "seed": iseed,
                "mask": (torch.zeros([a.batch_size, 1, 1, a.pose_length]) < 1).cuda(),
                "style_feature": torch.zeros([bs, 512]).cuda(),
            }}
            sample = self.model(cond)["latents"].squeeze().permute(1, 0).unsqueeze(0)
            last_sample = sample.clone()
            ru, rh, rl = sample[..., :128], sample[..., 128:256], sample[..., 256:]
            if i == 0:
                rec_up.append(ru); rec_hn.append(rh); rec_lo.append(rl)
            else:
                rec_up.append(ru[:, a.pre_frames:])
                rec_hn.append(rh[:, a.pre_frames:])
                rec_lo.append(rl[:, a.pre_frames:])

        rec_up = torch.cat(rec_up, dim=1) * self.vqvae_latent_scale
        rec_hn = torch.cat(rec_hn, dim=1) * self.vqvae_latent_scale
        rec_lo = torch.cat(rec_lo, dim=1) * self.vqvae_latent_scale
        rec_upper = self.vq_model_upper.latent2origin(rec_up)[0]
        rec_hands = self.vq_model_hands.latent2origin(rec_hn)[0]
        rec_lower = self.vq_model_lower.latent2origin(rec_lo)[0]

        if self.use_trans:
            rec_trans_v = rec_lower[..., -3:] * self.trans_std + self.trans_mean
            rec_trans = torch.cumsum(rec_trans_v, dim=-2)
            rec_trans[..., 1] = rec_trans_v[..., 1]
            rec_lower = rec_lower[..., :-3]

        if a.pose_norm:
            rec_upper = rec_upper * self.std_upper + self.mean_upper
            rec_hands = rec_hands * self.std_hands + self.mean_hands
            rec_lower = rec_lower * self.std_lower + self.mean_lower

        # re-combine upper / hands / lower into 165-d axis-angle pose
        bs_l, n_l = rec_lower.shape[0], rec_lower.shape[1]
        ru = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_upper.reshape(bs_l, n_l, 13, 6))
        ).reshape(bs_l * n_l, 13 * 3)
        rh = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_hands.reshape(bs_l, n_l, 30, 6))
        ).reshape(bs_l * n_l, 30 * 3)
        rl = rc.matrix_to_axis_angle(
            rc.rotation_6d_to_matrix(rec_lower[..., :54].reshape(bs_l, n_l, 9, 6))
        ).reshape(bs_l * n_l, 9 * 3)

        N = bs_l * n_l
        rec_pose = (self._inverse_selection(ru, self.joint_mask_upper, N)
                    + self._inverse_selection(rl, self.joint_mask_lower, N)
                    + self._inverse_selection(rh, self.joint_mask_hands, N))
        # keep jaw from target
        rec_pose[:, 66:69] = tar_pose.reshape(bs * n, 55 * 3)[:bs_l * n_l, 66:69]

        n = n - ((n - a.pre_frames * vsq) % (a.pose_length - a.pre_frames * vsq))
        return {
            "rec_pose_aa": rec_pose.reshape(bs_l, n_l, 165),  # axis-angle [bs, n, 165]
            "rec_trans": rec_trans,
            "tar_beta": loaded_data["tar_beta"][:, :n_l],
        }

    @torch.no_grad()
    def run_inference(self):
        self.model.eval()
        self.smplx.eval()
        for batch in self.test_loader:
            loaded = self._load_data(batch)
            return self._g_test(loaded)
        raise RuntimeError("test loader produced no batches")


# ===================================================================
# SMPLX → joint positions
# ===================================================================
@torch.no_grad()
def smplx_to_joints(smplx_model, rec_pose_aa, rec_trans, betas):
    """rec_pose_aa: [N, 165], rec_trans: [N, 3], betas: [300] → joints [N, 55, 3]."""
    N = rec_pose_aa.shape[0]
    aa = rec_pose_aa.reshape(N, 55, 3)
    body_betas = betas.unsqueeze(0).expand(N, -1).to(rec_pose_aa.device).float()
    out = smplx_model(
        betas=body_betas,
        global_orient=aa[:, 0],
        body_pose=aa[:, 1:22].reshape(N, 63),
        jaw_pose=aa[:, 22],
        leye_pose=aa[:, 23],
        reye_pose=aa[:, 24],
        left_hand_pose=aa[:, 25:40].reshape(N, 45),
        right_hand_pose=aa[:, 40:55].reshape(N, 45),
        transl=rec_trans.float(),
        expression=torch.zeros(N, 100, device=rec_pose_aa.device),
        return_verts=False,
    )
    return out.joints[:, :55].detach().cpu().numpy()  # [N, 55, 3]


# ===================================================================
# Main
# ===================================================================
ASR_PIPE = None  # lazily initialised in main


@logger.catch
def main():
    global ASR_PIPE
    args, cfg = config.parse_args()
    other_tools_hf.set_random_seed(args)

    out_dir = os.path.abspath(_my_args.out)
    os.makedirs(out_dir, exist_ok=True)
    logger.info(f"Output dir: {out_dir}")

    ASR_PIPE = pipeline(
        "automatic-speech-recognition",
        model="openai/whisper-tiny.en",
        chunk_length_s=30,
        device=DEVICE,
    )

    # Resolve GT npz path once: used both by the dataloader (as pose source) and
    # by the per-frame GT joint comparison below.
    gt_path = _my_args.gt or os.path.splitext(_my_args.audio)[0] + ".npz"
    if not os.path.exists(gt_path):
        raise FileNotFoundError(f"GT npz not found: {gt_path}")

    trainer = HTMLTrainer(args, cfg, audio_file=_my_args.audio, pose_file=gt_path)
    other_tools.load_checkpoints(trainer.model, args.test_ckpt, args.g_name)

    # ---- Generation ----
    out = trainer.run_inference()
    rec_pose_aa = out["rec_pose_aa"].reshape(-1, 165)
    rec_trans = out["rec_trans"].reshape(-1, 3)
    betas = out["tar_beta"][0, 0]
    gen_joints = smplx_to_joints(trainer.smplx, rec_pose_aa, rec_trans, betas)

    # ---- Ground truth ----
    gt = np.load(gt_path, allow_pickle=True)
    gt_pose_aa = torch.from_numpy(gt["poses"]).float().to(DEVICE)
    gt_trans = torch.from_numpy(gt["trans"]).float().to(DEVICE)
    gt_betas = torch.from_numpy(gt["betas"]).float().to(DEVICE)
    gt_joints = smplx_to_joints(trainer.smplx, gt_pose_aa, gt_trans, gt_betas)

    fps = int(args.pose_fps)

    # ---- Write canonical generation (rotations + translation + betas) ----
    np.savez(
        os.path.join(out_dir, "gen_rotation.npz"),
        poses=rec_pose_aa.detach().cpu().numpy(),
        trans=rec_trans.detach().cpu().numpy(),
        betas=betas.detach().cpu().numpy(),
        fps=np.int32(fps),
    )

    # ---- Write viewer-only joint positions ----
    np.savez(
        os.path.join(out_dir, "gen_position.npz"),
        joints=gen_joints,
        fps=np.int32(fps),
    )
    np.savez(
        os.path.join(out_dir, "gt_position.npz"),
        joints=gt_joints,
        fps=np.int32(fps),
    )

    # ---- Copy audio ----
    shutil.copy(_my_args.audio, os.path.join(out_dir, "speech.wav"))

    logger.info(
        f"Wrote {out_dir} "
        f"(gen {gen_joints.shape[0]} fr | gt {gt_joints.shape[0]} fr @ {fps} fps)"
    )
    logger.info(f"Open: {os.path.join(out_dir, 'visualize.html')}")


if __name__ == "__main__":
    main()
